fix: add parameters table to parse-build-deploy-script
ernesgonzalez33/rhtap-consoledot-frontend-build pull request #23
Opened 2024-01-18 07:53 UTC by ShakedAviv50313

2024-01-18 09:35 UTC, ernesgonzalez33 requested changes
@ShakedAviv50313 those are probably my fault. But can you solve the warnings in the yamllint? Also, can you add the Optional and Default value columns?

2024-01-18 09:38 UTC, ShakedAviv50313 commented
1. Wouldn't these lines be replaced once your newer PR gets merged?
2. sure, how can I tell which param is optional and their default values?
@ernesgonzalez33

2024-01-18 09:43 UTC, ernesgonzalez33 commented
> 1. Wouldn't these lines be replaced once your newer PR gets merged?
> 2. sure, how can I tell which param is optional and their default values?
>    @ernesgonzalez33

1. You are totally right. Forget it.
2. Check the parameters in the task. If there are no default values, it means is not optional

2024-02-01 09:15 UTC, ernesgonzalez33 approved these changes

2024-02-01 09:26 UTC, merged